[package]
name = "dol"
description = "A .dol file parser"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
elf = "0.8"
easyerr.workspace = true
binrw.workspace = true
