[package]
name = "gcwfmt"
description = "GameCube/Wii file formats"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
easyerr.workspace = true
binrw.workspace = true
zstd.workspace = true

elf = "0.8"
