[package]
name = "clif-incremental"
description = "Cranelift incremental cache storage"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
cranelift.workspace = true
cranelift-codegen.workspace = true

fjall = "3"
directories = "6"
