[package]
name = "ppcjit"
description = "JIT for Gekko PowerPC code using cranelift"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
gekko.workspace = true

bitos.workspace = true
easyerr.workspace = true
memmap2.workspace = true
rustc-hash.workspace = true
zerocopy.workspace = true
tracing.workspace = true

nix = { version = "0.30", features = ["mman"] }
cranelift = { version = "0.126", features = ["frontend", "native"] }
