[package]
name = "ppcjit"
description = "JIT for Gekko PowerPC code using cranelift"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
gekko.workspace = true

bitos.workspace = true
easyerr.workspace = true
rustc-hash.workspace = true
zerocopy.workspace = true
tracing.workspace = true

cranelift = { version = "0.126", features = ["frontend", "native"] }

[target.'cfg(windows)'.dependencies]
windows = { version = ">=0.59", features = [
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.30", features = ["mman"] }
