[package]
name = "ppcjit"
description = "JIT for Gekko PowerPC code using cranelift"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
disasm = ["dep:iced-x86"]

[dependencies]
gekko.workspace = true

bitos.workspace = true
easyerr.workspace = true
iced-x86 = { workspace = true, optional = true }
memmap2.workspace = true
rustc-hash.workspace = true
zerocopy.workspace = true
tracing.workspace = true
cranelift = { version = "0.125", features = ["frontend", "native"] }
