[package]
name = "hemisphere"
description = "The hemisphere emulator"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
gekko.workspace = true
dol.workspace = true
iso.workspace = true

bitos.workspace = true
bytesize.workspace = true
easyerr.workspace = true
slotmap.workspace = true
tracing.workspace = true
zerocopy.workspace = true
strum.workspace = true
glam.workspace = true
rustc-hash.workspace = true

backtrace = "0.3"
color-backtrace = "0.7"
parking_lot = "0.12"
