name: Nightly build

on:
  workflow_dispatch:
  schedule:
     - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Z threads=4 -Z share-generics=y

jobs:
  check_date:
    name: Check latest commit is recent enough
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_date.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5
      - name: Print latest commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  generate_name:
    name: Generate build artifact name
    runs-on: ubuntu-latest
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    outputs: 
      name: ${{ steps.generate_name.outputs.name }}
      date: ${{ steps.generate_date.outputs.date }}
      tag: ${{ steps.generate_tag.outputs.tag }}
    steps:
      - id: generate_name
        run: echo "name=hemisphere-linux-$(date -u +%y%m%d)" >> "$GITHUB_OUTPUT"
      - id: generate_date
        run: echo "date=$(date -u +%Y/%m/%d )" >> "$GITHUB_OUTPUT"
      - id: generate_tag
        run: echo "tag=nightly-$(date -u +%y%m%d)" >> "$GITHUB_OUTPUT"

  build:
    name: Build nightly release
    runs-on: ubuntu-latest
    needs: [check_date, generate_name]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update apt
        run: sudo apt-get update
      - name: Install audio deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          cache-on-failure: true
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build ipl-hle
        run: just ipl-hle build
      - name: Build hemisphere
        run: cargo build --release
      - name: Compress debug sections
        run: objcopy --compress-debug-sections=zstd ./target/release/app ./target/release/${{ needs.generate_name.outputs.name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate_name.outputs.name }}
          path: ./target/release/${{ needs.generate_name.outputs.name }}

  release:
    name: Create nightly release
    runs-on: ubuntu-latest
    needs: [check_date, generate_name, build]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.generate_name.outputs.name }}
          path: build
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Hemisphere Nightly (${{ needs.generate_name.outputs.date }})
          body: Nightly release ${{ needs.generate_name.outputs.date }}
          files: build/*
          tag_name: ${{ needs.generate_name.outputs.tag }}
          make_latest: true
          prerelease: false
